[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dockeasy"
dynamic = ["version"]
description = "docker made easy"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache-2.0"}
authors = [{name = "Karthik", email = "karthik.rajgopal@hotmail.com"}]
keywords = ['nbdev', 'docker', 'compose', 'containers', 'caddy', 'reverse proxy', 'web server', 'ssl', 'certificates']
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]
dependencies = [
    "fastcore>=1.12.30",
    "keyring>=25.7.0",
    "python-dotenv>=1.2.2",
    "notebook",
]

[project.urls]
Repository = "https://github.com/vedicreader/dockeasy"
Documentation = "https://vedicreader.github.io/dockeasy/"

[project.entry-points.nbdev]
dockeasy = "dockeasy._modidx:d"

[tool.hatch.version]
path = "dockeasy/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["dockeasy"]

[tool.hatch.build.targets.sdist]
include = [
    "/dockeasy",
    "/README.md",
    "/pyproject.toml",
]

[tool.nbdev]

[dependency-groups]
dev = [
    "ipyai>=0.0.8",
    "koshas>=0.0.3",
    "nbdev>=3.0.12",
]
