"""Caddy reverse proxy, CrowdSec security, swag containers and Cloudflare tunnel support"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_proxy.ipynb.

# %% auto #0
__all__ = ['Caddyfile', 'caddy', 'caddy_api', 'caddy_svc', 'cloudflared_svc', 'crowdsec', 'caddy_sqlite_dockerfile',
           'caddy_sqlite_svc']

# %% ../nbs/01_proxy.ipynb #e67b555b
from fastcore.all import L, store_attr, listify, joins, Path
from .core import *

# %% ../nbs/01_proxy.ipynb #94648fec2ab8bd32
class Caddyfile(L):
	'Fluent builder for production-ready Caddyfiles'
	def __init__(self, domain, app='app', port=5001):
		store_attr()
		super().__init__([])

	def _new(self, items):
		c = type(self)(self.domain, self.app, self.port)
		c.items = items
		return c

	def _add(self, *s): return self._new(self.items + list(s))
	def _has(self, tag): return any(t == tag for t, _ in self)
	def _get(self, tag): return L(self).filter(lambda x: x[0] == tag).itemgot(1)
	def __repr__(self): return str(self)

	def email(self, addr):
		'ACME account email (global). Caddy works without it but uses anonymous account.'
		return self._add(('g', f'email {addr}'))

	def acme_dns(self, provider, token_env=None):
		'DNS-01 TLS challenge — needed when port 80 is unavailable (e.g. behind Cloudflare tunnel)'
		token = f'{{${token_env}}}' if token_env else ''
		return self._add(('s', f'\ttls {{\n\t\tacme_dns {provider} {token}\n\t}}'))

	def cloudflared(self):
		'Use http:// prefix — required when running behind cloudflared tunnel (no public port 80/443)'
		return self._add(('f', 'cloudflared'))

	def crowdsec(self, api_url='http://crowdsec:8080', key_env='CROWDSEC_API_KEY'):
		'CrowdSec bouncer — plugin, not built-in'
		return self._add(('s', f'\tcrowdsec {{\n\t\tapi_url {api_url}\n\t\tapi_key {{${key_env}}}\n\t}}'))

	def rate_limit(self, requests='100', window='1m'):
		'Rate limiting'
		return self._add(('s', f'\trate_limit {{\n\t\tzone dynamic {{\n\t\t\tkey {{http.request.remote_ip}}\n\t\t\tevents {requests}\n\t\t\twindow {window}\n\t\t}}\n\t}}'))

	def max_body(self, size='100m'):
		'Request body limit'
		return self._add(('s', f'\trequest_body {{\n\t\tmax_size {size}\n\t}}'))

	def spa(self, static_dir='/app/static'):
		'SPA preset: static files with fallback to index.html'
		return self._add(('spa', f'\troot * {static_dir}\n\ttry_files {{path}} /index.html\n\tfile_server'))

	def encode(self):
		'Compression — Caddy does NOT enable this by default, one word is enough'
		return self._add(('s', '\tencode'))

	def log(self, output='stderr'):
		'Access logging. Caddy logs errors by default; access logs are opt-in.'
		out = f'output {output}' if output != 'stderr' else ''
		return self._add(('s', f'\tlog {{\n\t\t{out}\n\t}}' if out else '\tlog'))

	def route(self, path, app, port):
		'Path-based handle block: handle /path/* { reverse_proxy app:port }'
		return self._add(('r', (path, app, port)))

	def sqlite_router(self, db, query="SELECT host, port FROM routes WHERE domain = :domain"):
		'Dynamic subdomain routing via SQLite DB (requires caddy-sqlite-router plugin)'
		return self._add(('sqlite', (db, query)))

	def __str__(self):
		'Render full Caddyfile'
		parts = []
		g = list(self._get('g'))
		if g: parts.append('{\n\t' + '\n\t'.join(g) + '\n}')
		prefix = 'http://' if self._has('f') else ''
		site = [f'{prefix}{self.domain} {{'] + listify(self._get('s'))
		if self._has('spa'): site += listify(self._get('spa'))
		elif self._has('sqlite'):
			db, query = listify(self._get('sqlite'))[0]
			site.append(f'\troute {{\n\t\tsqlite_router {db} "{query}"\n\t\treverse_proxy {{http.vars.backend_upstream}}\n\t}}')
		elif self._has('r'):
			for path, app, port in self._get('r'):
				site.append(f'\thandle {path} {{\n\t\treverse_proxy {app}:{port}\n\t}}')
			site.append(f'\thandle {{\n\t\treverse_proxy {self.app}:{self.port}\n\t}}')
		else: site.append(f'\treverse_proxy {self.app}:{self.port}')
		site.append('}')
		parts.append('\n'.join(site))
		return '\n'.join(parts)

	def save(self, path='Caddyfile'):
		'Write to disk'
		Path(path).write_text(str(self))
		return self

# %% ../nbs/01_proxy.ipynb #d1a11e12
def caddy(domain,  # domain to serve (e.g. example.com or sub.example.com)
          app='app',  # upstream app name (must match Compose service name)
          port=5001,  # upstream app port
          email=None,  # ACME account email (optional but good practice)
          dns=None,  # DNS-01 provider name for TLS when port 80 is blocked (e.g. 'cloudflare' or 'duckdns')
          dns_token_env=None,  # env var name for DNS API token (default: {DNS}_API_TOKEN)
          crowdsec=False,  # enable CrowdSec bouncer plugin
          crowdsec_url='http://crowdsec:8080',  # CrowdSec API URL
          cloudflared=False,  # prefix with http:// for Cloudflare tunnel setups
          encode=False,  # enable compression
          access_log=False,  # enable access logging to stderr
          routes=None,  # dict {'/path/*': ('svc', port)} for path-based multi-service routing
          )->Caddyfile:
	'Minimal Caddyfile for reverse-proxying app:port from domain. Optional ACME email, DNS-01, CrowdSec, Cloudflare tunnel, and multi-service path routing.'
	cf = Caddyfile(domain, app, port)
	if email: cf = cf.email(email)
	if dns and not cloudflared: cf = cf.acme_dns(dns, dns_token_env or f'{dns.upper()}_API_TOKEN')
	if cloudflared: cf = cf.cloudflared()
	if crowdsec: cf = cf.crowdsec(api_url=crowdsec_url)
	if encode: cf = cf.encode()
	if access_log: cf = cf.log()
	if routes:
		for path, (svc, p) in routes.items(): cf = cf.route(path, svc, p)
	return cf

def caddy_api(domain,
              app='app',
              port=5001,
              email=None,
              dns=None,
              dns_token_env=None,
              cloudflared=False,
              crowdsec=False,
              crowdsec_url='http://crowdsec:8080',
              max_body='50m',
              rate='200',
              rate_window='1m',
              routes=None,  # dict {'/path/*': ('svc', port)} for path-based multi-service routing
              ) -> str:
	'Caddyfile preset for API services — adds rate limiting and body size cap'
	return caddy(domain, app, port, email=email, dns=dns, dns_token_env=dns_token_env,
                 cloudflared=cloudflared, crowdsec=crowdsec, crowdsec_url=crowdsec_url,
                 routes=routes).rate_limit(rate, rate_window).max_body(max_body).encode()

# %% ../nbs/01_proxy.ipynb #2aaa95f8
def _caddy_img(crowdsec, cloudflare):
    if crowdsec and cloudflare: return 'ghcr.io/buildplan/csdp-caddy:latest'
    elif crowdsec: return 'serfriz/caddy-crowdsec:latest'
    elif cloudflare: return 'serfriz/caddy-cloudflare:latest'
    else: return 'caddy:2'

def caddy_svc(domain, app='app', port=5001, *, dns=None, email=None,
              crowdsec=False, cloudflared=False, conf='Caddyfile',
              routes=None,  # dict {'/path/*': ('svc', port)} — adds services to depends_on
              **kw):
    'Write Caddyfile and return Caddy service kwargs for Compose.svc()'
    caddy(domain, app, port, email=email, dns=dns, cloudflared=cloudflared,
          crowdsec=crowdsec, routes=routes).save(conf)
    is_cf = dns == 'cloudflare'
    tok = f'{dns.upper()}_API_TOKEN' if dns else None
    env = {}
    if dns: env[tok] = '${%s}' % tok
    if crowdsec: env['CROWDSEC_API_KEY'] = '${CROWDSEC_API_KEY}'
    conf_path = Path(conf)
    vol_key = str(conf_path.resolve()) if conf_path.is_absolute() else f'./{conf_path.name}'
    deps = [app] + [svc for svc, _ in (routes or {}).values()]
    return service(
        image=kw.pop('image', _caddy_img(crowdsec, is_cf)),
        ports=None if cloudflared else ['80:80', '443:443', '443:443/udp'],
        env=env or None,
        volumes={vol_key: '/etc/caddy/Caddyfile', 'caddy_data': '/data', 'caddy_config': '/config'},
        depends_on=deps, networks=['web'], restart='unless-stopped', **kw
    )

# %% ../nbs/01_proxy.ipynb #52a33e28
def cloudflared_svc(token_env='${CF_TUNNEL_TOKEN}', url=None, **kw):
    'Cloudflare tunnel service kwargs for Compose.svc(). Pass url to set ingress inline (e.g. url="http://caddy").'
    cmd = f'tunnel --no-autoupdate run{" --url " + url if url else ""}'
    return service(image='cloudflare/cloudflared:latest', command=cmd,
                   env={'TUNNEL_TOKEN': token_env}, networks=['web'], restart='unless-stopped', **kw)

# %% ../nbs/01_proxy.ipynb #a63a6718
def crowdsec(collections=None, bouncer_key_env='CROWDSEC_BOUNCER_KEY', **kw):
    'CrowdSec agent service kwargs for Compose.svc()'
    cols = joins(' ', listify(collections or ['crowdsecurity/linux', 'crowdsecurity/caddy', 'crowdsecurity/http-cve']))
    return service(
        image='crowdsecurity/crowdsec:latest',
        env={'COLLECTIONS': cols, 'BOUNCER_KEY_caddy': f'${{{bouncer_key_env}}}'},
        volumes={'crowdsec-db': '/var/lib/crowdsec/data', 'crowdsec-config': '/etc/crowdsec'},
        networks=['web'], restart='unless-stopped', **kw
    )

# %% ../nbs/01_proxy.ipynb #ccy4ciozn7n
def caddy_sqlite_dockerfile():
    'Multi-stage Dockerfile: Caddy + caddy-sqlite-router plugin (requires CGO via xcaddy)'
    return (Dockerfile()
            .from_('caddy:2-builder', as_='builder')
            .run('apk add --no-cache gcc musl-dev')
            .run('CGO_ENABLED=1 xcaddy build --with github.com/AnswerDotAI/caddy-sqlite-router')
            .from_('caddy:2-alpine')
            .copy('/usr/bin/caddy', '/usr/bin/caddy', from_='builder'))

def caddy_sqlite_svc(domain, db='/data/routes.db', image='caddy-sqlite:latest', *,
                     query="SELECT host, port FROM routes WHERE domain = :domain",
                     email=None, crowdsec=False, conf='Caddyfile', **kw):
    'Caddy service with SQLite dynamic subdomain routing. Build image with caddy_sqlite_dockerfile(). db is the in-container path; mount it via **kw volumes.'
    cf = Caddyfile(domain)
    if email: cf = cf.email(email)
    if crowdsec: cf = cf.crowdsec()
    cf.sqlite_router(db, query).save(conf)
    conf_path = Path(conf)
    vol_key = str(conf_path.resolve()) if conf_path.is_absolute() else f'./{conf_path.name}'
    env = {'CROWDSEC_API_KEY': '${CROWDSEC_API_KEY}'} if crowdsec else None
    return service(
        image=image, ports=['80:80', '443:443', '443:443/udp'],
        env=env,
        volumes={vol_key: '/etc/caddy/Caddyfile', 'caddy_data': '/data', 'caddy_config': '/config'},
        networks=['web'], restart='unless-stopped', **kw
    )
