"""One call to host N apps on a single VPS — each on its own subdomain, routed live via SQLite."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_tenant.ipynb.

# %% auto #0
__all__ = ['CADDY_SQLITE_IMAGE', 'sync_routes', 'tenant_stack']

# %% ../nbs/02_tenant.ipynb #b1a41cb6fac7
from fastcore.all import Path, L
from .core import detect_app, Compose
from .proxy import caddy_sqlite_dockerfile, caddy_sqlite_svc, cloudflared_svc
import sqlite3, re

# %% ../nbs/02_tenant.ipynb #598713e17b77
def _detect_port(path):
    'Infer app port from project files by reading EXPOSE from the detected Dockerfile'
    m = re.search(r'^EXPOSE (\d+)', str(detect_app(path)), re.MULTILINE)
    return int(m.group(1)) if m else 5001

# %% ../nbs/02_tenant.ipynb #b0e4681b5d4b
def sync_routes(tenants_dir='./tenants', db='routes.db', prune=False):
    'Scan tenants_dir for app subdirs and upsert routes DB. prune=True removes rows for missing dirs.'
    tenants_dir = Path(tenants_dir)
    subdirs = {d.name: d for d in sorted(tenants_dir.iterdir()) if d.is_dir() and not d.name.startswith('.')}
    con = sqlite3.connect(db)
    con.execute('''CREATE TABLE IF NOT EXISTS routes
                   (domain TEXT PRIMARY KEY, host TEXT NOT NULL, port INTEGER NOT NULL)''')
    existing = {r[0] for r in con.execute('SELECT domain FROM routes')}
    for name, d in subdirs.items():
        if name not in existing:
            con.execute('INSERT INTO routes VALUES (?,?,?)', (name, name, _detect_port(d)))
    if prune:
        for name in existing - subdirs.keys():
            con.execute('DELETE FROM routes WHERE domain = ?', (name,))
    con.commit()
    result = {r[0]: (r[1], r[2]) for r in con.execute('SELECT domain, host, port FROM routes')}
    con.close()
    return result

# %% ../nbs/02_tenant.ipynb #5ff7a2de9cf0
CADDY_SQLITE_IMAGE = 'ghcr.io/vedicreader/caddy-sqlite:latest'
_CADDY_BUILD_DIR   = '.caddy-sqlite'

def tenant_stack(base_domain, tenants_dir='./tenants', *,
                 db='routes.db', cloudflared=True, crowdsec=False,
                 conf='Caddyfile', caddy_image=CADDY_SQLITE_IMAGE,
                 prune=False, **kw):
    '''Multi-tenant compose stack — scans tenants_dir, syncs routes DB, builds missing Dockerfiles,
    and returns a wired Compose with caddy-sqlite + optional cloudflared/crowdsec.

    caddy_image defaults to ghcr.io/vedicreader/caddy-sqlite:latest (pre-built in CI via
    .github/workflows/caddy-sqlite.yml). If the image is not cached locally, compose builds
    it from .caddy-sqlite/Dockerfile using xcaddy (takes 3-5 min on first run).'''
    tenants_dir = Path(tenants_dir)
    routes = sync_routes(tenants_dir, db, prune=prune)
    for name in routes:
        d = tenants_dir/name
        if not (d/'Dockerfile').exists():
            detect_app(str(d)).save(d/'Dockerfile')
    caddy_dir = Path(_CADDY_BUILD_DIR)
    caddy_dir.mkdir(exist_ok=True)
    caddy_sqlite_dockerfile().save(caddy_dir/'Dockerfile')
    dc = Compose()
    for name in routes:
        dc = dc.svc(name, build=str(tenants_dir/name), networks=['web'], restart='unless-stopped')
    caddy_kw = caddy_sqlite_svc(f'*.{base_domain}', db='/routes.db',
                                 image=caddy_image, build=str(caddy_dir),
                                 crowdsec=crowdsec, conf=conf)
    caddy_kw['volumes'].append(f'{Path(db).resolve()}:/routes.db')
    dc = dc.svc('caddy', **caddy_kw)
    if cloudflared: dc = dc.svc('cloudflared', **cloudflared_svc())
    return dc.network('web').volume('caddy_data').volume('caddy_config')
